name: Send LINE Notification

on:
  schedule:
    # 8時間ごとに実行 (UTC)
    - cron: '0 */8 * * *'
    # 毎週日曜日の12:00 (UTC) に実行 (日本時間の21:00)
    - cron: '0 12 * * 0'
  # 手動でも実行できるようにする
  workflow_dispatch:
    inputs:
      task:
        description: 'Run a specific task'
        required: true
        default: 'daily_notify'
        type: choice
        options:
          - daily_notify
          - weekly_summary
          - setup_rich_menu

jobs:
  # 毎時の記事チェックと通知ジョブ
  notify:
    if: github.event.schedule == '0 */8 * * *' || (github.event_name == 'workflow_dispatch' && inputs.task == 'daily_notify')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: curl, mbstring, simplexml, json, pdo_pgsql
      - name: Run daily script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          GEMINI_MODELS: ${{ secrets.GEMINI_MODELS }}
          SCRAPING_API_KEY: ${{ secrets.SCRAPING_API_KEY }}
        run: php scripts/run_daily.php

  # 週間サマリーの送信ジョブ
  send_summary:
    if: github.event.schedule == '0 12 * * 0' || (github.event_name == 'workflow_dispatch' && inputs.task == 'weekly_summary')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: curl, mbstring, simplexml, json, pdo_pgsql
      - name: Run weekly summary script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          GEMINI_MODELS: ${{ secrets.GEMINI_MODELS }}
        run: php scripts/run_weekly.php

  # リッチメニュー設定ジョブ
  setup_rich_menu:
    if: github.event_name == 'workflow_dispatch' && inputs.task == 'setup_rich_menu'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: curl
      - name: Run rich menu setup script
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        run: php scripts/setup_rich_menu.php