name: Send LINE Notification

on:
  # 1時間ごとに自動実行 (UTC)
  schedule:
    - cron: '0 * * * *'
  # 手動でも実行できるようにする
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    # 自動コミットするために書き込み権限を付与
    permissions:
      contents: write

    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. PHP環境をセットアップ
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: curl, mbstring, simplexml # 必要なPHP拡張

      # 3. PHPスクリプトを実行
      - name: Run PHP script
        env:
          # GitHubのSecretsから認証情報を環境変数として渡す
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: php run.php

      # 4. last_notified_url.txtの変更を自動コミット
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: Update last notified URL'
          file_pattern: 'last_notified_url_*.txt'
